"""Generic, professional presentation of a test-suite report as an email.

Pure formatting only - no I/O, no transport, no configuration, and **no
knowledge of any particular use case**. These builders render a small,
use-case-agnostic view model (:class:`EmailReport`) into the email subject,
plain-text body, and HTML body. Each use case is responsible for mapping its own
result model into an :class:`EmailReport` (via its own
``to_email_report()``); this module only knows how to render that view.

:mod:`apppilot.email_delivery` owns recipient handling, authentication, and
delivery, and delegates all presentation here so the concerns stay cleanly
separated.

The rendered email keeps a clean, professional layout: a product header, a suite
summary, a compact results table (whatever columns the view supplies), an
optional per-case Details section, and a small footer with an optional contact
address. Every dynamic value in the HTML is escaped, and the plain-text and HTML
bodies carry the same facts.
"""

from __future__ import annotations

import html
from dataclasses import dataclass, field
from typing import Optional, Sequence


# --------------------------------------------------------------------------- #
# View model (use-case-agnostic). A use case maps its own results into these.
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Cell:
    """One results-table cell. ``status`` (when set) renders a PASS/FAIL pill
    and ``text`` is ignored; otherwise ``text`` is shown (HTML-escaped)."""

    text: str = ""
    muted: bool = False
    center: bool = False
    nowrap: bool = False
    status: Optional[bool] = None


@dataclass(frozen=True)
class DetailAttempt:
    """One attempt line inside a Details card: a label, a pass/fail chip, and
    free text (e.g. the sanitized reason)."""

    label: str
    ok: bool
    text: str


@dataclass(frozen=True)
class DetailCard:
    """One case's Details card: a title, verdict, a small badge, a single
    labeled meta field, and its per-attempt lines."""

    title: str
    passed: bool
    badge: str = ""
    meta_label: str = ""
    meta_value: str = ""
    attempts: Sequence[DetailAttempt] = field(default_factory=tuple)


@dataclass(frozen=True)
class EmailReport:
    """Everything the renderer needs, with zero use-case coupling.

    ``summary_segments`` are short secondary-summary strings (rendered as
    separate lines in text and joined inline in HTML). ``columns``/``rows`` are
    the compact results table. ``details`` is the optional per-case section.
    ``body_text`` is the detailed plain-text report (the console report, used
    verbatim as the source of truth for the plain-text body)."""

    suite_name: str
    total: int
    passed: int
    failed: int
    summary_segments: Sequence[str] = field(default_factory=tuple)
    columns: Sequence[str] = field(default_factory=tuple)
    rows: Sequence[Sequence[Cell]] = field(default_factory=tuple)
    details: Sequence[DetailCard] = field(default_factory=tuple)
    body_text: str = ""


def _status(view: EmailReport) -> str:
    return "PASS" if view.failed == 0 else "FAIL"


def _contact(contact: Optional[str]) -> Optional[str]:
    """Normalize the optional contact address; blank/None means 'not set'."""
    if not contact:
        return None
    contact = contact.strip()
    return contact or None


# --------------------------------------------------------------------------- #
# Subject
# --------------------------------------------------------------------------- #
def build_subject(view: EmailReport) -> str:
    """Suite verdict and pass ratio, e.g.
    ``AppPilot <Suite> Suite: FAIL (3/4 passed)``. The suite name comes from
    the view (``view.suite_name``), not hardcoded."""
    return (
        f"AppPilot {view.suite_name} Suite: {_status(view)} "
        f"({view.passed}/{view.total} passed)"
    )


# --------------------------------------------------------------------------- #
# Plain text
# --------------------------------------------------------------------------- #
_SEP = "-" * 60


def build_text_body(view: EmailReport, contact: Optional[str] = None) -> str:
    """Summary header (suite result + any secondary segments), the detailed
    report text (the source of truth), then a small footer."""
    lines = [
        f"Suite result: {_status(view)}",
        f"Total cases: {view.total}",
        f"Passed: {view.passed}   Failed: {view.failed}",
    ]
    lines.extend(view.summary_segments)
    lines += ["", _SEP, ""]
    footer = [
        "",
        _SEP,
        "Generated by AppPilot - Automated Test Reporting",
    ]
    address = _contact(contact)
    if address:
        footer.append(f"Contact: {address}")
    return "\n".join(lines) + view.body_text + "\n" + "\n".join(footer)


# --------------------------------------------------------------------------- #
# HTML (inline styles only - email clients strip <style>/external CSS)
# --------------------------------------------------------------------------- #
_FONT = "font-family:'Segoe UI',Arial,sans-serif;"
_TEXT = "#202124"
_MUTED = "#5f6368"
_LINE = "#e0e0e0"
_ROW_LINE = "#eeeeee"
_PASS = "#1e7e34"
_FAIL = "#c62828"
_PASS_BG = "#e6f4ea"
_FAIL_BG = "#fce8e6"

_TH = (
    f"text-align:left;padding:8px 10px;background:#f5f6f7;color:{_TEXT};"
    f"font-weight:600;font-size:12px;border-bottom:2px solid {_LINE};"
)
_TD = f"padding:8px 10px;border-bottom:1px solid {_ROW_LINE};vertical-align:top;"


def _esc(value) -> str:
    return html.escape(str(value))


def _pill(passed: bool) -> str:
    label = "PASS" if passed else "FAIL"
    bg = _PASS_BG if passed else _FAIL_BG
    fg = _PASS if passed else _FAIL
    return (
        f'<span style="display:inline-block;padding:2px 10px;border-radius:3px;'
        f'background:{bg};color:{fg};font-weight:600;">{label}</span>'
    )


def _attempt_chip(matched: bool) -> str:
    label = "match" if matched else "mismatch"
    bg = _PASS_BG if matched else _FAIL_BG
    fg = _PASS if matched else _FAIL
    return (
        f'<span style="display:inline-block;padding:1px 8px;border-radius:10px;'
        f'background:{bg};color:{fg};font-size:11px;font-weight:600;'
        f'text-transform:uppercase;letter-spacing:0.3px;">{label}</span>'
    )


def _render_cell(cell: Cell) -> str:
    style = _TD
    if cell.nowrap:
        style += "white-space:nowrap;"
    if cell.muted:
        style += f"color:{_MUTED};"
    if cell.center:
        style += "text-align:center;white-space:nowrap;"
    inner = _pill(cell.status) if cell.status is not None else _esc(cell.text)
    return f'<td style="{style}">{inner}</td>'


def _results_table(columns: Sequence[str], rows: Sequence[Sequence[Cell]]) -> str:
    headers = "".join(f'<th style="{_TH}">{_esc(col)}</th>' for col in columns)
    body = "".join(
        "<tr>" + "".join(_render_cell(cell) for cell in row) + "</tr>"
        for row in rows
    )
    return (
        '<table style="border-collapse:collapse;width:100%;font-size:13px;">'
        f"<thead><tr>{headers}</tr></thead>"
        f"<tbody>{body}</tbody></table>"
    )


def _details(cards: Sequence[DetailCard]) -> str:
    rendered = []
    for card in cards:
        accent = _PASS if card.passed else _FAIL
        attempts = "".join(
            '<div style="margin:8px 0 0;padding-top:8px;'
            f'border-top:1px solid {_ROW_LINE};">'
            f'<div style="margin:0 0 3px;">'
            f'<span style="color:{_MUTED};font-size:12px;font-weight:600;">'
            f"{_esc(a.label)}</span> &nbsp;{_attempt_chip(a.ok)}</div>"
            f'<div style="color:#3c4043;font-size:13px;">{_esc(a.text)}</div>'
            "</div>"
            for a in card.attempts
        )
        rendered.append(
            f'<div style="border:1px solid {_LINE};border-left:3px solid {accent};'
            'border-radius:5px;padding:12px 14px;margin:0 0 10px;">'
            '<div style="margin:0 0 6px;">'
            f'<b style="font-size:14px;">{_esc(card.title)}</b>'
            f"&nbsp;&nbsp;{_pill(card.passed)}"
            f'&nbsp;&nbsp;<span style="color:{_MUTED};font-size:12px;">'
            f"{_esc(card.badge)}</span></div>"
            f'<div style="color:{_MUTED};font-size:13px;">'
            f'<span style="color:#80868b;">{_esc(card.meta_label)}:</span> '
            f"{_esc(card.meta_value)}</div>"
            f"{attempts}</div>"
        )
    return (
        '<div style="font-weight:600;margin:24px 0 10px;font-size:15px;">'
        "Details</div>" + "".join(rendered)
    )


def build_html_body(view: EmailReport, contact: Optional[str] = None) -> str:
    """Clean, professional HTML email: product header, suite summary, the
    results table, an optional Details section, and a small footer with an
    optional contact line. Inline styles only. Same facts as
    :func:`build_text_body`."""
    suite_color = _PASS if view.failed == 0 else _FAIL

    parts = [
        '<html><head><meta charset="utf-8"></head>'
        '<body style="margin:0;padding:0;background:#ffffff;">',
        f'<div style="max-width:760px;margin:0 auto;padding:24px;{_FONT}'
        f'color:{_TEXT};font-size:14px;line-height:1.5;">',
        '<div style="font-size:18px;font-weight:600;">AppPilot</div>',
        f'<div style="color:{_MUTED};font-size:13px;">'
        f"{_esc(view.suite_name)} Suite Report</div>",
        f'<hr style="border:none;border-top:1px solid {_LINE};margin:16px 0;">',
        '<div style="margin:0 0 4px;">Suite result: '
        f'<b style="color:{suite_color};">{_status(view)}</b> '
        f"&mdash; {view.passed}/{view.total} passed</div>",
    ]
    if view.summary_segments:
        summary = " &nbsp;|&nbsp; ".join(_esc(s) for s in view.summary_segments)
        parts.append(
            f'<div style="color:{_MUTED};margin:0 0 16px;">{summary}</div>'
        )
    parts.append(_results_table(view.columns, view.rows))
    if view.details:
        parts.append(_details(view.details))
    parts += [
        f'<hr style="border:none;border-top:1px solid {_LINE};margin:24px 0 12px;">',
        f'<div style="color:{_MUTED};font-size:12px;">'
        "Generated by AppPilot &middot; Automated Test Reporting</div>",
    ]
    address = _contact(contact)
    if address:
        esc = _esc(address)
        parts.append(
            f'<div style="color:{_MUTED};font-size:12px;">Contact: '
            f'<a href="mailto:{esc}" style="color:{_MUTED};">{esc}</a></div>'
        )
    parts += ["</div>", "</body></html>"]
    return "".join(parts)
